version: '2'
services:
  client:
    build: .
    container_name: notes-keeper
    environment:
      ConnectionStrings__DefaultConnection: $connectionString
      ASPNETCORE_ENVIRONMENT: Development
    restart: always
    ports:
      - 5555:80
  db:
    image: postgres
    restart: always
    container_name: notes-keeper-bd
    environment:
      POSTGRES_PASSWORD: $password
      POSTGRES_USER: $user
    ports:
      - 5554:5432